[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm install -g @angular/cli@18',
    'npm ci --legacy-peer-deps --no-audit --no-optional'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_OPTIONS='--max-old-space-size=4096'
NPM_CONFIG_LEGACY_PEER_DEPS='true'
CI='true'
HUSKY='0'
CYPRESS_INSTALL_BINARY='0'