[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm install -g @angular/cli@16',
    'npm install --legacy-peer-deps --no-audit'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_OPTIONS='--max-old-space-size=2048'
NPM_CONFIG_LEGACY_PEER_DEPS='true'
CI='true'